-- Find likely keep pool canidates and return the DDL to utilize them.
--
CREATE TABLE TEMP_TAB AS
   SELECT O.OWNER          OWNER,
          O.OBJECT_NAME    OBJECT_NAME,
          O.SUBOBJECT_NAME SUBOBJECT_NAME,
          O.OBJECT_TYPE    OBJECT_TYPE,
          COUNT(DISTINCT FILE# || BLOCK#)         NUM_BLOCKS
     FROM DBA_OBJECTS  O, V$BH         BH
    WHERE O.DATA_OBJECT_ID  = BH.OBJD
      AND O.OWNER NOT IN ('SYS','SYSTEM','SYSAUX','FLOWS_020100','ORDSYS','MGMT_VIEW','FLOWS_030000','SYSMAN','DBSNMP','XDB')
      AND BH.STATUS != 'FREE'
 GROUP BY O.OWNER, O.OBJECT_NAME, O.SUBOBJECT_NAME, O.OBJECT_TYPE
 ORDER BY COUNT(DISTINCT FILE# || BLOCK#) DESC;
--
SELECT 'ALTER '||S.SEGMENT_TYPE||' '||T.OWNER||'.'||S.SEGMENT_NAME||' STORAGE (BUFFER_POOL KEEP);' POOL_CANIDATES
  FROM TEMP_TAB T, DBA_SEGMENTS S
 WHERE S.SEGMENT_NAME = T.OBJECT_NAME
   AND S.OWNER = T.OWNER
   AND S.SEGMENT_TYPE = T.OBJECT_TYPE
   AND NVL(S.PARTITION_NAME,'-') = NVL(T.SUBOBJECT_NAME,'-')
   AND BUFFER_POOL <> 'KEEP'
   AND OBJECT_TYPE IN ('TABLE','INDEX') 
   AND T.OWNER='GDOSYS'
GROUP BY S.SEGMENT_TYPE, T.OWNER, S.SEGMENT_NAME
HAVING (SUM(NUM_BLOCKS)/GREATEST(SUM(BLOCKS), .001))*100 > 80;
DROP TABLE TEMP_TAB;
--